@api_url = http://localhost:4000/api


### Create Content
POST {{api_url}}/contents
Content-Type: application/json

{
  "title": "How to Start A Blog in 2025",
  "description": "After completing this guide you will have a beautiful blog that is ready to share with the world. This guide is made especially for beginners. I will walk you through each and every step, using plenty of pictures and videos to make it all perfectly clear. If you get stuck or have questions at any point, simply send me a message and I will do my best to help you out."
}


### Update Content
PUT {{api_url}}/contents
Content-Type: application/json

{
  "id": "838f92b0-615c-40bd-9d0b-8dce15b90254",
  "title": "Updated Sample Content",
  "description": "This is an updated description for the content."
}


### Get All Content
GET {{api_url}}/contents
Content-Type: application/json


### Get Content by ID
GET {{api_url}}/contents/d472a824-62e7-4898-9442-03d3d3d2ca1b
Content-Type: application/json